var namespacesgl =
[
    [ "Bellman", "classsgl_1_1_bellman.html", "classsgl_1_1_bellman" ],
    [ "Bellman< true, type_wt, Edge, Graph, Tree >", "classsgl_1_1_bellman_3_01true_00_01type__wt_00_01_edge_00_01_graph_00_01_tree_01_4.html", "classsgl_1_1_bellman_3_01true_00_01type__wt_00_01_edge_00_01_graph_00_01_tree_01_4" ],
    [ "BFS", "classsgl_1_1_b_f_s.html", "classsgl_1_1_b_f_s" ],
    [ "Bipartite_list", "classsgl_1_1_bipartite__list.html", "classsgl_1_1_bipartite__list" ],
    [ "Comp_Flow", "classsgl_1_1_comp___flow.html", "classsgl_1_1_comp___flow" ],
    [ "Comp_MST", "classsgl_1_1_comp___m_s_t.html", "classsgl_1_1_comp___m_s_t" ],
    [ "Comp_SP", "classsgl_1_1_comp___s_p.html", "classsgl_1_1_comp___s_p" ],
    [ "Connectivity", "classsgl_1_1_connectivity.html", "classsgl_1_1_connectivity" ],
    [ "Cut_Vertices", "classsgl_1_1_cut___vertices.html", "classsgl_1_1_cut___vertices" ],
    [ "DFS", "classsgl_1_1_d_f_s.html", "classsgl_1_1_d_f_s" ],
    [ "Dijkstra", "classsgl_1_1_dijkstra.html", "classsgl_1_1_dijkstra" ],
    [ "Edge_Base", "classsgl_1_1_edge___base.html", "classsgl_1_1_edge___base" ],
    [ "Edge_Flow", "classsgl_1_1_edge___flow.html", "classsgl_1_1_edge___flow" ],
    [ "Edge_Weight", "classsgl_1_1_edge___weight.html", "classsgl_1_1_edge___weight" ],
    [ "Effeuiller", "classsgl_1_1_effeuiller.html", "classsgl_1_1_effeuiller" ],
    [ "Fulkerson", "classsgl_1_1_fulkerson.html", "classsgl_1_1_fulkerson" ],
    [ "Graph_List", "classsgl_1_1_graph___list.html", "classsgl_1_1_graph___list" ],
    [ "Graph_Matrix", "classsgl_1_1_graph___matrix.html", "classsgl_1_1_graph___matrix" ],
    [ "IO", "classsgl_1_1_i_o.html", null ],
    [ "isBipartite", "classsgl_1_1is_bipartite.html", "classsgl_1_1is_bipartite" ],
    [ "Kruskal", "classsgl_1_1_kruskal.html", "classsgl_1_1_kruskal" ],
    [ "Max_Flow", "classsgl_1_1_max___flow.html", "classsgl_1_1_max___flow" ],
    [ "MaxMatching_Graph", "classsgl_1_1_max_matching___graph.html", "classsgl_1_1_max_matching___graph" ],
    [ "NoNullCap", "classsgl_1_1_no_null_cap.html", "classsgl_1_1_no_null_cap" ],
    [ "Preflow", "classsgl_1_1_preflow.html", "classsgl_1_1_preflow" ],
    [ "Prim", "classsgl_1_1_prim.html", "classsgl_1_1_prim" ],
    [ "Proc_Base", "classsgl_1_1_proc___base.html", "classsgl_1_1_proc___base" ],
    [ "Proc_Max_Depth", "classsgl_1_1_proc___max___depth.html", "classsgl_1_1_proc___max___depth" ],
    [ "Rdm_Graph", "classsgl_1_1_rdm___graph.html", "classsgl_1_1_rdm___graph" ],
    [ "SCC", "classsgl_1_1_s_c_c.html", "classsgl_1_1_s_c_c" ],
    [ "SearchVertex", "classsgl_1_1_search_vertex.html", "classsgl_1_1_search_vertex" ],
    [ "Splitting", "classsgl_1_1_splitting.html", null ],
    [ "TC", "classsgl_1_1_t_c.html", "classsgl_1_1_t_c" ],
    [ "Topological_Sort", "classsgl_1_1_topological___sort.html", "classsgl_1_1_topological___sort" ],
    [ "Tree_Dist", "classsgl_1_1_tree___dist.html", "classsgl_1_1_tree___dist" ],
    [ "Tree_List", "classsgl_1_1_tree___list.html", "classsgl_1_1_tree___list" ],
    [ "TSP", "classsgl_1_1_t_s_p.html", "classsgl_1_1_t_s_p" ]
];